import React from 'react'

// Body wraps page content and ensures it's not hidden under the sticky header.
// It adds top padding equal to the header height and provides a responsive container.
const Main = () => {
  return (
    <main className={`pt-16 md:pt-20 `}>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam illo cupiditate consequatur, debitis maiores minus iusto expedita a doloremque praesentium velit accusantium aut molestias quae at, eius eligendi minima vel!
      Amet illum consequatur non et, nobis esse in ut aliquid impedit odit illo voluptates enim inventore veniam quos ab eum voluptatem doloribus alias blanditiis adipisci explicabo expedita quis dicta! Recusandae.
      Quod, laudantium animi incidunt consectetur vero consequatur unde fuga, dolores dicta enim amet earum quos rem laborum. Esse, tempora? Dolorem et inventore cum qui illum sapiente nisi, iste voluptate deserunt.
      Nisi non enim omnis amet quaerat deleniti quibusdam. Porro non iure repellendus et sapiente ut necessitatibus. Vel quisquam laborum porro iusto molestiae magni quasi! Culpa saepe aliquam voluptatem unde dicta?
      Ut veniam tempora facere tempore natus. Voluptatem placeat error animi quaerat voluptates cumque expedita, accusantium libero vel! Eius debitis autem similique expedita facilis id, laborum libero at, aliquid ipsa consequatur.
      Provident maiores ut cupiditate eligendi similique aut voluptates excepturi nisi voluptatem! Assumenda, eos provident voluptate pariatur neque fugiat numquam, vero dolorem, enim similique deleniti. Temporibus magni asperiores debitis consectetur? Obcaecati?
      Iste ut repudiandae alias non vitae fugit dignissimos sapiente, amet optio accusantium? Accusantium asperiores dignissimos earum aspernatur debitis animi dolor, repellat excepturi quis cumque ut voluptatibus fugit nobis. Pariatur, reiciendis.
      Eos nulla labore tempore molestias accusantium corrupti autem quisquam doloremque excepturi deserunt debitis animi adipisci, quis illo rem quod, vero expedita ab accusamus? Fugit molestiae a impedit placeat ea sed?
      Architecto id aut vel iure? Exercitationem obcaecati vitae, reiciendis suscipit sit quisquam molestiae omnis, veritatis ut, provident accusamus autem odio. Reprehenderit, dolores nihil maiores esse aliquid praesentium est libero facilis.
      Veritatis sint tempore natus ut suscipit magnam modi deserunt atque, aspernatur, molestiae consequuntur eos quos doloribus consequatur deleniti, autem laborum. Tenetur provident sapiente laborum, sit iusto commodi ex corrupti ea!
      Asperiores saepe aspernatur assumenda quis fuga pariatur, libero illum? Soluta amet enim atque quia perspiciatis, maxime ex minus impedit architecto ipsum nulla aut sunt, ducimus beatae ut, quasi est. Expedita!
      Dicta possimus exercitationem quae obcaecati earum odio. Excepturi aspernatur magni rerum animi sed architecto sit, facilis ea consectetur dolorum eius dignissimos dolorem obcaecati, velit illo quisquam, saepe eligendi. Quas, fugiat.
      Odio nihil enim sapiente soluta excepturi eaque ut est unde deleniti vel odit quisquam natus vero possimus, modi molestias. Odit et sint vero. Quibusdam beatae ex reiciendis natus quam consectetur.
      Voluptas animi eum repudiandae beatae consequatur necessitatibus officiis nisi hic expedita. Repellat asperiores blanditiis velit, perferendis eligendi ducimus veritatis vel omnis, neque aperiam nostrum totam. Fugit nostrum exercitationem alias odio!
      Tempora rerum consectetur quisquam? Temporibus in aliquam beatae nisi facilis aliquid mollitia tenetur iure, nesciunt consequatur, dolorum ipsam a molestias eum numquam non ea dolore quidem sit repellendus reprehenderit officiis!
      Iusto, totam odio eveniet ducimus reprehenderit voluptas, natus laboriosam error impedit maiores sequi amet, dolores consectetur porro aspernatur fuga atque excepturi consequuntur est! Quasi praesentium vero rem soluta inventore vitae?
      Explicabo harum accusamus iste officia perspiciatis error delectus impedit ducimus sapiente quos ipsam quibusdam id expedita obcaecati, perferendis odio temporibus ad, aut soluta a. Commodi laborum quo fugit provident laudantium!
      Iure repellendus quos, qui consequatur deserunt ipsam. Recusandae quos earum quae repudiandae rem, similique nostrum. Voluptatem quam in enim nam laborum eius magnam, odit ab iusto ut doloribus omnis doloremque.
      Atque laborum voluptas dolore adipisci suscipit tenetur. Eum facilis recusandae alias corporis eligendi at fuga, quas repellendus architecto dolorem tempore vel obcaecati doloremque minima quos consequatur voluptatibus. Alias, reprehenderit explicabo?
      Assumenda, nam reiciendis. Distinctio accusantium eveniet aliquid quos! Quidem eveniet molestias corporis eaque ipsa soluta facere omnis reiciendis cumque odio atque aperiam eius sed architecto debitis ducimus, quia consequuntur corrupti.
      Deserunt, quasi nesciunt quae ipsa, fuga iure quos nostrum, minima quod a assumenda porro provident repudiandae ut quia soluta! Nihil necessitatibus unde consequatur qui repellat similique ipsam, nam odio saepe.
      Numquam eius minima voluptatibus molestiae ipsam quod alias voluptas illum unde. In quibusdam, nam incidunt necessitatibus accusantium eius illum commodi distinctio voluptate mollitia, velit voluptas vel numquam praesentium doloremque quod?
      Vel itaque aperiam odit unde hic inventore eius modi veniam labore! Dolorem commodi quae, officiis aperiam impedit similique esse consectetur accusamus, quos labore sunt doloremque odit. Sunt repellat reprehenderit accusamus!
      Maxime atque quo nemo in nesciunt dolores aliquam itaque earum eligendi rem accusamus, quam neque laboriosam repellat velit numquam, assumenda minima aut! Inventore aspernatur temporibus qui ad, placeat ipsum? Ab.
      Eos est blanditiis accusantium! Quae velit aspernatur, quibusdam exercitationem animi harum qui suscipit atque nesciunt eligendi totam consectetur. Laborum maxime, numquam porro doloribus illum non fugit atque tenetur totam perferendis.
      Repellat molestiae asperiores vero modi placeat ut aperiam in ipsam aspernatur? Ab, nisi nam corporis labore laborum similique? Doloribus voluptas sunt magnam aut nobis amet iste nisi voluptatum voluptate? Corrupti.
      Voluptates doloribus magni dignissimos ad sunt quaerat soluta odit eaque dicta laborum, hic quo dolorem et ab illum aliquid id. Nostrum vitae deleniti quidem nemo libero nihil eligendi, tempora suscipit.
      Deserunt quo ratione nobis nihil error doloremque quae consequuntur, reprehenderit veritatis! Voluptas deleniti assumenda suscipit dolores molestiae? Assumenda sint debitis nam adipisci voluptates natus officia cum laboriosam, ad nulla delectus.
      Laudantium quam asperiores assumenda, quisquam atque quod odio aspernatur sint nesciunt, iusto nulla saepe vel eaque est quis tenetur. Natus esse quisquam quasi ullam. Omnis dolorum aliquam laboriosam nisi necessitatibus.
      Id veniam sunt labore, quia corporis eos ducimus iste illo quaerat, quibusdam dolor ab corrupti commodi in mollitia laudantium magnam optio dolore iure eum odit nihil? Omnis tenetur dicta id.
      Porro saepe incidunt maxime quis quos rem optio fugit, earum ad dolores quae, enim eum suscipit eos culpa provident officiis dolore, natus voluptas laudantium nam minus doloremque id ipsa? Ut.
      Nesciunt, ducimus. Repellat quis nulla aperiam inventore ratione necessitatibus, quia natus officia deleniti quos, quo sapiente odio iusto sed ipsum exercitationem sint neque laudantium, atque deserunt rerum facilis. Quaerat, voluptate.
      Temporibus id quas ex tempore fugit inventore officiis nisi ratione quam laboriosam, cumque delectus ipsam, eius adipisci suscipit possimus reprehenderit pariatur nesciunt repudiandae sunt iste, voluptas asperiores consequuntur dignissimos. Et!
      Voluptatum error cumque optio quaerat. Explicabo illo tempore neque, vel deleniti dignissimos vero hic ullam sapiente, sit facere obcaecati magnam id perspiciatis nam repudiandae consectetur porro aspernatur sed? Molestiae, molestias!
      Necessitatibus, earum temporibus voluptatem odit numquam nam suscipit cumque, facilis quisquam cum vero modi laborum maxime vitae impedit? Quam asperiores facere hic, veniam qui amet! Nesciunt sed vero ad rem!
      Perferendis, suscipit officiis ipsam eaque in numquam quibusdam assumenda sit aspernatur ut quae harum provident vitae autem placeat nesciunt expedita commodi aut delectus porro amet cumque ab molestiae laudantium. Quam.
      Mollitia eum harum vero voluptatum nam dicta odio iste rem nisi maiores aliquam recusandae culpa, sequi numquam blanditiis qui nulla beatae cupiditate velit deleniti tenetur impedit! Fugit esse unde nostrum!
      Molestiae consectetur fugit iusto fugiat nulla dicta sit est placeat, temporibus numquam. Laudantium nesciunt vel, reprehenderit voluptas error autem doloremque explicabo dicta minus similique quaerat hic atque dolorem sit totam!
      Voluptate explicabo saepe et nisi repellat, magni reprehenderit harum ea! Delectus blanditiis dolores facilis deleniti numquam totam architecto consequuntur quis quo reiciendis aut explicabo, minima odit eaque quas voluptas. Saepe!
      Iure architecto eaque nemo sint, dicta facilis qui possimus, deleniti consequatur vel ipsam neque modi repellendus. Recusandae nisi ducimus omnis, nostrum, quos est vel cupiditate, ut voluptas suscipit veritatis quibusdam?
      Sit rem officia quia distinctio incidunt quam aliquid expedita dolorem sapiente quod tempora quo quibusdam molestiae voluptas saepe doloribus eaque maiores, inventore quas temporibus dolore? Odio dolorum in eius corrupti.
      Tenetur a porro eum iusto, perspiciatis, quaerat est fugiat quibusdam ullam exercitationem neque eius pariatur? Facilis iusto dolor optio aliquid accusamus ipsa exercitationem rerum ipsum. Quo odit fugit dicta maiores?
      Molestias hic at tempora atque accusamus ipsum repellat voluptas, itaque nam, sint dicta soluta veniam facilis ut nostrum quidem est perferendis! Fugiat ullam maiores id explicabo voluptatem distinctio nihil commodi.
      Nisi veniam aperiam natus mollitia obcaecati cum non asperiores aliquid sit, dolore, harum est libero, exercitationem vitae? Ullam ipsam nobis provident numquam quae? Veritatis est necessitatibus odit eveniet itaque cum?
      Saepe, voluptatum molestias. Laudantium mollitia ipsam cumque fugiat sint, saepe eos amet quis eius quas eligendi quam minima harum nemo. Minus adipisci culpa distinctio aliquid laborum, reiciendis sint mollitia nisi.
      Dolor fugiat aspernatur nobis dolorum rem, sint repudiandae incidunt asperiores velit tenetur temporibus itaque dolores voluptatibus repellat modi exercitationem esse! Excepturi officia porro illo dolorem, totam fuga magnam odio voluptatibus.
      Autem dolorum molestias, iste animi molestiae temporibus fugit suscipit eum nostrum! Excepturi voluptatem debitis corporis tempora sed, doloremque autem cumque corrupti quas suscipit, nostrum iste? Sit veritatis rerum in odio.
      Maiores libero sapiente harum culpa autem at cum, voluptates natus velit laboriosam quae eveniet modi ipsum eum soluta voluptatibus. Repudiandae omnis assumenda perferendis nemo quia exercitationem reiciendis, asperiores similique tenetur.
      Quidem delectus similique animi eum odio quibusdam nulla vel pariatur ut inventore. Accusantium iste beatae reiciendis illum magni ducimus animi iure repellendus vero debitis, accusamus fugiat eaque doloribus laudantium libero?
      Natus est, ex perferendis fuga suscipit quos commodi tenetur officia nemo repellendus non id iste. Assumenda nam ducimus soluta fuga nulla laudantium, incidunt vitae quis dolorum omnis ipsam qui saepe!
      Quas nemo, aliquam repellendus error assumenda praesentium consequatur eveniet incidunt nobis! Consequuntur delectus enim veniam porro odit dolorem ipsum deleniti saepe, ea distinctio! Qui, facere. Optio neque quas accusantium autem?
      Quis quas totam laudantium quasi omnis ipsa laboriosam eos delectus exercitationem! Doloribus quibusdam laboriosam aperiam perferendis sapiente, nobis ratione quas! Veritatis, obcaecati quia! Quibusdam eum sunt nulla necessitatibus voluptas eligendi.
      Vitae deleniti voluptate sunt inventore. Eveniet mollitia vero laboriosam laudantium labore voluptatum quos autem ad nobis amet consequatur illo nulla, dolores similique, officia fuga esse ea itaque, impedit magni non.
      Esse voluptatibus nobis, ratione fugiat adipisci saepe corporis fuga explicabo? Officia eaque repellendus quo beatae, officiis quos autem earum sit, nesciunt asperiores, aperiam non modi! Quasi delectus odit neque tempora.
      Harum magni aut deleniti maiores sapiente quae ab modi. Magni corrupti distinctio, exercitationem non qui molestias quas nulla enim facilis! Neque inventore cumque ratione cum praesentium maxime id voluptas nihil.
      Deleniti, omnis natus! Sed libero commodi nulla temporibus quod odit at vitae totam dolorem sint impedit, dolorum suscipit maiores fuga, eligendi omnis adipisci dolore enim id unde quis aspernatur dolores.
      Saepe consequuntur amet ratione cupiditate ipsa natus nemo pariatur architecto aliquam autem magnam adipisci ea asperiores eligendi tempore nulla deleniti voluptatem repudiandae delectus, aperiam expedita neque illo soluta? Autem, adipisci?
      Asperiores esse amet nemo. Corporis totam voluptate tenetur tempore ratione. Minima esse explicabo, a aliquid quae pariatur rerum earum soluta perspiciatis, possimus illo minus? Nihil modi non excepturi cum corporis.
      Nulla velit minus quisquam. Animi, ratione. Iste ex unde modi minima. Dolores cumque recusandae ipsum perferendis at laborum incidunt, nesciunt unde illum porro enim ut quisquam ipsam fugit magni sint.
      Molestias, odio necessitatibus minima nam beatae, expedita maiores porro dolorem odit, similique ducimus in corporis eius hic? Maxime dicta culpa perspiciatis iure, ipsum nobis voluptatum voluptatibus incidunt necessitatibus blanditiis totam?
      Qui cumque, quibusdam quam nulla, commodi totam facilis magni explicabo quae perferendis sed voluptatem doloribus sapiente, ipsum molestias a labore corporis recusandae quos ducimus et accusamus tempora. Doloremque, earum in.
      Maiores, cupiditate? Odio, numquam magnam ipsa deleniti fuga sequi laudantium ut facere. Animi magnam voluptatibus eligendi a cum officia! Aut, perferendis assumenda ipsam dignissimos eius a omnis vitae cumque in?
      Natus ea, beatae incidunt vero ipsa exercitationem doloribus iusto reiciendis perspiciatis veniam sed assumenda rem cumque libero asperiores obcaecati unde, rerum ipsam at, repellendus a qui explicabo culpa! Fugit, tempora.
      Expedita provident laborum illo! Magni reprehenderit quis velit soluta placeat itaque eius tenetur est optio, mollitia laboriosam, id perspiciatis. Atque eaque enim animi blanditiis quaerat illum aliquam corrupti nulla corporis.
      Repudiandae facere quia ut, esse corrupti minus id, obcaecati magni ipsam alias deserunt vel est? Ex magnam magni rem voluptatibus eligendi earum accusamus? Accusamus, tempore explicabo. Nostrum eveniet dolor sunt?
      Unde vitae molestiae sunt veritatis, commodi sit saepe quo impedit iusto libero quos repellendus corrupti mollitia fuga quia alias consectetur dignissimos modi, quam suscipit! Vitae odio odit laudantium praesentium non!
      Rem ullam tempora odio molestias distinctio eaque amet magnam aperiam fugiat quas. Quibusdam pariatur amet molestiae saepe dicta at aut cum, ipsum praesentium fugiat a enim esse. Laudantium, officia repellendus.
      Dolorum ea cum harum nisi cumque vel, quas repellat eveniet accusantium voluptas. Modi minus asperiores vero ipsum ea id quidem, nihil voluptates harum cumque nisi itaque est aperiam expedita deleniti?
      Eius perferendis officia maiores, ut nisi consequatur laborum sint itaque culpa placeat, fugit veniam tempore suscipit asperiores similique nihil atque amet odit cumque nam inventore reprehenderit, numquam id nemo. Sunt!
      Maiores, nihil fugiat temporibus laboriosam qui, deleniti ut exercitationem consequuntur molestias laudantium vitae omnis! Excepturi dignissimos eius dolor quis sit voluptatum? Earum aperiam similique laudantium, illum amet quidem quae repudiandae.
      Nobis possimus sequi excepturi natus mollitia at laudantium! Ipsum iusto nobis eaque suscipit hic, nulla rerum natus accusamus earum eos, quo obcaecati corporis! Est dolore doloremque hic quos sequi iste?
      Nostrum beatae reprehenderit repellat quo dolorem tempore facilis? Cupiditate excepturi, a tempore ducimus magni modi. Explicabo delectus officiis ea dolorum. Rerum sunt amet natus quos nemo labore nisi fuga atque.
      Perspiciatis dolores sunt facilis voluptas deserunt, accusamus neque, tempore optio eligendi provident recusandae quos. Repudiandae at pariatur deleniti provident! Laborum repellendus commodi omnis inventore voluptate doloribus incidunt praesentium sed natus?
      Tempore numquam tenetur, in sequi doloribus optio qui praesentium maiores! Velit earum numquam veritatis cumque natus quod delectus ad odio doloremque ea! Commodi ullam possimus error nihil. Dolorem, harum ipsam!
      At illum vero harum obcaecati saepe, quidem sapiente? Voluptate a placeat soluta voluptas eius. Nobis voluptatem ducimus molestiae hic unde alias voluptas autem enim debitis, numquam aut, nam blanditiis obcaecati!
      Delectus, cupiditate! Nemo ratione odit sequi deleniti inventore consequatur vero maxime obcaecati aspernatur saepe, aperiam amet fuga repellendus modi praesentium officiis nulla nam cumque placeat, quaerat pariatur necessitatibus temporibus possimus!
      Mollitia laboriosam exercitationem ratione est ad atque illum tenetur dignissimos incidunt voluptas iure provident vel accusantium, aliquam quam quae quo? Dolorem incidunt quos iusto. Nesciunt neque natus cupiditate blanditiis cumque.
      Eos ex itaque ipsa amet facilis, incidunt optio commodi laborum dicta, mollitia minima. Illo cumque libero asperiores eum pariatur ullam, repellat voluptates impedit nam sit facilis sunt laudantium omnis repudiandae?
      Obcaecati consequatur id laudantium illum, accusamus, fugit facilis saepe voluptas natus minus, eligendi qui officia dolorum. Optio fugit deleniti dignissimos, veritatis dolorum adipisci blanditiis dicta, minus reprehenderit quae voluptatibus alias?
      Esse, ad animi? Exercitationem provident sapiente hic dicta soluta enim minus dignissimos. Ipsum ex, esse magni animi minima fugiat perspiciatis velit accusantium consequuntur delectus temporibus ea assumenda quidem id distinctio?
      Dolorem, sint dolores doloribus possimus quos deserunt quo, autem voluptas nam expedita et! Tempora nihil voluptas provident non earum, vero mollitia accusamus saepe vitae illum perferendis cum distinctio architecto minima.
      Nihil sequi iusto laboriosam, possimus dolorum debitis. Eum ipsam ab saepe! Eos sed dolorum corporis voluptates pariatur ab vero excepturi facilis illum iure. Enim necessitatibus at dolorum. Quae, itaque obcaecati?
      Iusto voluptates, saepe possimus mollitia temporibus magni quia minima nemo! Molestias, excepturi natus saepe quos dolorem pariatur quo nobis fugit commodi recusandae perspiciatis? Asperiores quo non accusantium iure repudiandae incidunt.
      Unde ab, sapiente sit velit cumque harum ut quasi accusantium suscipit autem error exercitationem nobis minus, esse sed quos consequuntur. Totam inventore amet dolore earum qui pariatur accusantium alias illo.
      Labore illo id quas, ducimus possimus magni incidunt in veniam neque qui aut fugiat nam modi quisquam nulla eligendi laborum distinctio architecto? Deserunt laboriosam autem earum, laudantium doloribus quia facilis.
      Eaque aliquam rerum perspiciatis tenetur sed, corporis odio sint vitae quae quibusdam, tempora eum magni nostrum, dolorum similique quasi saepe neque natus nesciunt cum rem culpa veniam? Qui, pariatur harum.
      Blanditiis eum commodi molestias quia voluptas nemo cum totam dolor. Corrupti inventore aliquid fugiat saepe dolorem architecto ipsam minus suscipit odio! Molestias, voluptate? Quos excepturi nobis non, amet recusandae quidem?
      Laboriosam ut aperiam molestiae enim corrupti! Ut odio aliquam voluptatem rerum, praesentium ea labore repellendus et sequi commodi est exercitationem porro, eligendi deserunt officiis dolorem. Accusamus repudiandae corrupti sit quos.
      Suscipit eligendi sed porro magni reiciendis, cumque perferendis reprehenderit enim tempora maxime. Ut cum aspernatur sunt enim commodi sapiente debitis! Fugiat sequi accusamus reiciendis enim incidunt? Nemo qui recusandae aperiam?
      Dignissimos eum mollitia, quod asperiores, maxime fuga obcaecati, perspiciatis eos nam culpa cum earum necessitatibus dolorum quaerat quisquam impedit labore commodi nihil molestiae assumenda! Omnis, quas modi. Dolorum, aliquid eaque?
      Incidunt voluptatem laborum modi nam officia sed iste praesentium odio enim aliquam fuga, a aspernatur voluptates adipisci similique pariatur nisi nemo voluptas tenetur distinctio neque eius? Magnam rem at animi.
      Pariatur, natus obcaecati deleniti molestias officiis voluptates commodi ratione similique. Eum recusandae dignissimos ex omnis ipsum accusantium delectus dicta cumque veniam magnam. Voluptate labore illo necessitatibus nostrum iste odio est?
      Debitis rerum voluptates a ipsum deleniti pariatur consectetur quisquam adipisci veniam, fugit quos vitae voluptatum soluta ut eum earum incidunt, facilis aspernatur harum maiores dolore! Fugit iste minima quaerat possimus.
      Ab, deserunt veritatis? Explicabo nobis quo iste saepe asperiores necessitatibus quia neque pariatur recusandae autem est sit animi odio molestias quasi, sequi rem a rerum cum libero modi at. Recusandae?
      Similique, id. Dolorum odio debitis beatae sunt consequuntur non ratione corporis reiciendis suscipit quis libero, ipsa tempora. Laboriosam atque eligendi quis deserunt reprehenderit minima cum illum cumque, suscipit nobis. Ab!
      Illo voluptate vel molestias beatae fugit atque earum pariatur perferendis obcaecati. Aperiam reiciendis at nostrum. Quasi natus accusantium ipsam quo aperiam dolor, porro soluta corrupti magni pariatur sapiente nihil quae!
      Accusantium eius omnis iure quae sed eligendi, ipsa, nisi modi quas recusandae commodi itaque natus, excepturi culpa beatae at veritatis suscipit earum quidem corrupti! Cumque beatae labore veritatis sint optio?
      Perferendis illum autem voluptate ducimus sit temporibus aut adipisci quo ipsum rerum libero dolorum aperiam quam, vel praesentium optio exercitationem eos explicabo ad ipsam omnis ullam. Illum quaerat quam non.
      Natus fugiat, eaque ratione sunt sequi earum dicta atque enim praesentium eius numquam. Voluptatibus ex veritatis numquam laudantium rem iste est dicta officiis! Id magnam officia tempora. Quae, iusto laudantium.
      Laboriosam harum accusamus officia iusto ipsam sed, autem, reiciendis, reprehenderit repudiandae nesciunt esse beatae eum? Molestiae rem aut itaque facere labore ab, excepturi debitis repellendus, ducimus temporibus quos sequi beatae.
    </main> 
  )
}

export default Main
